/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_springjni_JNIWrapper */

#ifndef _Included_com_example_springjni_JNIWrapper
#define _Included_com_example_springjni_JNIWrapper
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     com_example_springjni_JNIWrapper
 * Method:    sum
 * Signature: (II)I
 */
  JNIEXPORT jint JNICALL Java_com_example_springjni_JNIWrapper_sum(JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
